USE [master]
GO

/****** Object:  Database [GISLicenseTrack]    Script Date: 06/10/2015 13:36:00 ******/
CREATE DATABASE [GISLicenseTrack] ON  PRIMARY 
( NAME = N'GISLicenseTrack', FILENAME = N'G:\SQLDATA\GISLicenseTrack.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 15360KB )
 LOG ON 
( NAME = N'GISLicenseTrack_log', FILENAME = N'G:\SQLDATA\GISLicenseTrack_log.ldf' , SIZE = 20096KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO

ALTER DATABASE [GISLicenseTrack] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GISLicenseTrack].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [GISLicenseTrack] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET ARITHABORT OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [GISLicenseTrack] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GISLicenseTrack] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GISLicenseTrack] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GISLicenseTrack] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GISLicenseTrack] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GISLicenseTrack] SET  READ_WRITE 
GO

ALTER DATABASE [GISLicenseTrack] SET RECOVERY FULL 
GO

ALTER DATABASE [GISLicenseTrack] SET  MULTI_USER 
GO

ALTER DATABASE [GISLicenseTrack] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GISLicenseTrack] SET DB_CHAINING OFF 
GO

